import { Place } from '../types';

export const PLACES_MOCK: Place[] = [
  {
    id: 1,
    name: 'Калик Мята Lounge',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.2,
    location: 'Ул. Советская 12',
  },
  {
    id: 2,
    name: 'Smoke & Chill',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.8,
    location: 'Проспект Мира 101',
  },
  {
    id: 3,
    name: 'Ароматный Вечер',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.5,
    location: 'Ул. Ленина 45',
  },
  {
    id: 4,
    name: 'Hookah & Relax',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.0,
    location: 'Ул. Пушкина 2',
  },
  {
    id: 5,
    name: 'Хмельной Дымок',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.7,
    location: 'Ул. Горького 17',
  },
  {
    id: 6,
    name: 'Mellow Smoke',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 3.9,
    location: 'Ул. Чехова 90',
  },
  {
    id: 7,
    name: 'Туманный Берег',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.6,
    location: 'Ул. Советская 44',
  },
  {
    id: 8,
    name: 'Лунная Кальянная',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.3,
    location: 'Ул. Кирова 8Б',
  },
  {
    id: 9,
    name: 'Smooth Hookah Spot',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.9,
    location: 'Ул. Молодёжная 37',
  },
  {
    id: 10,
    name: 'Ночной Огонёк',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.1,
    location: 'Ул. Спортивная 11',
  },
  {
    id: 11,
    name: 'Мята Вечерняя',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.4,
    location: 'Пр. Космонавтов 50',
  },
  {
    id: 12,
    name: 'Hookah House Deluxe',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.2,
    location: 'Ул. Гоголя 13А',
  },
  {
    id: 13,
    name: 'Ароматные Ночи',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.8,
    location: 'Ул. Бажова 3',
  },
  {
    id: 14,
    name: 'Chill Zone',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 3.8,
    location: 'Ул. Труда 76',
  },
  {
    id: 15,
    name: 'Тихий Пар',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.6,
    location: 'Ул. Мира 22',
  },
  {
    id: 16,
    name: 'Дымная Гавань',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.7,
    location: 'Ул. Первомайская 19',
  },
  {
    id: 17,
    name: 'Night Sky Hookah',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.3,
    location: 'Ул. Парковая 5',
  },
  {
    id: 18,
    name: 'Сказочный Пар',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.9,
    location: 'Ул. Лесная 71',
  },
  {
    id: 19,
    name: 'Городской Дым',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.1,
    location: 'Ул. Комсомольская 100',
  },
  {
    id: 20,
    name: 'Mint Oasis',
    photo: 'https://shtaer.ru/wp-content/uploads/2019/09/myata.jpg',
    rating: 4.5,
    location: 'Ул. Заречная 9',
  },
];
